import test from 'node:test';
import assert from 'node:assert/strict';
import {onRequest,validateFilters} from '../functions/api/library/[[path]].js';
const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_ANON_KEY:'public-key'};
test('unauthenticated search and preview never contact storage or database',async()=>{for(const path of ['search','preview/'+'a'.repeat(64)+':1']){let called=false;const original=globalThis.fetch;globalThis.fetch=async()=>{called=true;throw Error('unexpected')};try{const r=await onRequest({request:new Request('https://example.com/api/library/'+path),env});assert.equal(r.status,401);assert.equal(called,false);assert.match(r.headers.get('Cache-Control'),/no-store/)}finally{globalThis.fetch=original}}});
test('signed-in nonowner cannot read metadata or previews',async()=>{const original=globalThis.fetch;globalThis.fetch=async url=>String(url).endsWith('/user')?Response.json({id:'other',email_confirmed_at:'2026-01-01'}):Response.json(false);try{for(const path of ['bootstrap','search','preview/'+'a'.repeat(64)+':1']){const r=await onRequest({request:new Request('https://example.com/api/library/'+path,{headers:{Authorization:'Bearer token'}}),env});assert.equal(r.status,403)}}finally{globalThis.fetch=original}});
test('cross-origin writes are denied before data is touched',async()=>{const r=await onRequest({request:new Request('https://example.com/api/library/collections',{method:'POST',headers:{Authorization:'Bearer token',Origin:'https://evil.example','Content-Type':'application/json'},body:'{"name":"x"}'}),env});assert.equal(r.status,403)});
test('filters are bounded and combined without changing their meaning',()=>{assert.deepEqual(validateFilters({grade:3,topic:'broeker',difficulty:'let'}),{grade:'3',topic:'broeker',difficulty:'let'});for(const input of [null,[],{grade:99},{difficulty:'anything'},{q:'x'.repeat(201)},{collection:'not-a-uuid'},{topic:"x');drop table"}])assert.throws(()=>validateFilters(input))});
test('owner search passes a single filter object to the database',async()=>{const original=globalThis.fetch;let captured;globalThis.fetch=async(url,options)=>{if(String(url).endsWith('/user'))return Response.json({id:'owner',email_confirmed_at:'2026-01-01'});if(String(url).endsWith('/math_is_owner'))return Response.json(true);captured=JSON.parse(options.body);return Response.json({total:1,items:[]})};try{const r=await onRequest({request:new Request('https://example.com/api/library/search?grade=3&topic=broeker&difficulty=let',{headers:{Authorization:'Bearer token'}}),env});assert.equal(r.status,200);assert.deepEqual(captured.p_filters,{grade:'3',topic:'broeker',difficulty:'let'});assert.equal(captured.p_limit,30)}finally{globalThis.fetch=original}});
