import test from 'node:test';
import assert from 'node:assert/strict';
import {onRequest,validateFilters} from '../functions/api/library/[[path]].js';
const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_ANON_KEY:'public-key'};
test('public search works without auth and does not forward visitor credentials',async()=>{const original=globalThis.fetch;let captured;globalThis.fetch=async(url,options)=>{captured={url:String(url),headers:options.headers};return Response.json({total:1,items:[]})};try{const r=await onRequest({request:new Request('https://example.com/api/library/search',{headers:{Authorization:'Bearer stale-visitor-token'}}),env});assert.equal(r.status,200);assert.ok(captured.url.endsWith('/rpc/math_search'));assert.equal(captured.headers.Authorization,undefined);assert.equal(captured.headers.apikey,'public-key')}finally{globalThis.fetch=original}});

test('public preview resolves a validated page through private storage',async()=>{const original=globalThis.fetch;let key;globalThis.fetch=async()=>Response.json([{preview_key:'known/page.jpg'}]);try{const r=await onRequest({request:new Request('https://example.com/api/library/preview/'+'a'.repeat(64)+':1'),env:{...env,MATH_PREVIEWS:{get:async k=>{key=k;return {body:new Uint8Array([255,216,255])}}}}});assert.equal(r.status,200);assert.equal(key,'known/page.jpg');assert.equal(r.headers.get('Content-Type'),'image/jpeg')}finally{globalThis.fetch=original}});

test('cross-origin writes are denied before data is touched',async()=>{const r=await onRequest({request:new Request('https://example.com/api/library/collections',{method:'POST',headers:{Authorization:'Bearer token',Origin:'https://evil.example','Content-Type':'application/json'},body:'{"name":"x"}'}),env});assert.equal(r.status,403)});
test('filters are bounded and combined without changing their meaning',()=>{assert.deepEqual(validateFilters({grade:3,topic:'broeker',difficulty:'let'}),{grade:'3',topic:'broeker',difficulty:'let'});for(const input of [null,[],{grade:99},{difficulty:'anything'},{q:'x'.repeat(201)},{collection:'not-a-uuid'},{topic:"x');drop table"}])assert.throws(()=>validateFilters(input))});
test('public search passes filters and only supported page sizes to the database',async()=>{const original=globalThis.fetch;let captured;globalThis.fetch=async(url,options)=>{captured=JSON.parse(options.body);return Response.json({total:1,items:[]})};try{for(const [limit,expected] of [['',100],['200',200],['300',300],['9999',100],['bogus',100]]){const r=await onRequest({request:new Request('https://example.com/api/library/search?grade=3&topic=broeker&difficulty=let'+(limit?'&limit='+limit:'')),env});assert.equal(r.status,200);assert.deepEqual(captured.p_filters,{grade:'3',topic:'broeker',difficulty:'let'});assert.equal(captured.p_limit,expected)}}finally{globalThis.fetch=original}});
