import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/jacob/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base=process.argv[2]||'https://matematikbibliotek-preview.eastwood451-com.pages.dev';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const response=await page.goto(base+'/matematikbibliotek/',{waitUntil:'networkidle'});assert.equal(response.status(),200);assert.ok(response.headers()['content-security-policy']?.includes("frame-ancestors 'none'"));
await page.locator('.card').first().waitFor({timeout:30000});
assert.equal(await page.locator('#login').count(),0);
const result=await page.evaluate(async()=>{const started=performance.now();const r=await fetch('/api/library/search?grade=3&topic=broeker&difficulty=let');return {status:r.status,ms:Math.round(performance.now()-started),value:await r.json()}});
assert.equal(result.status,200);assert.ok(Array.isArray(result.value.items));
const preview=await page.evaluate(async()=>{const r=await fetch('/api/library/search');const s=await r.json();const item=s.items.find(i=>i.preview_key);if(!item)return null;const p=await fetch('/api/library/preview/'+encodeURIComponent(item.page_id));return {status:p.status,type:p.headers.get('Content-Type'),bytes:(await p.arrayBuffer()).byteLength}});
assert.ok(preview);assert.equal(preview.status,200);assert.equal(preview.type,'image/jpeg');assert.ok(preview.bytes>1000);
assert.deepEqual(errors,[]);
await page.screenshot({path:'E:/Codex @Barracuda/Matematikbibliotek-data/preview-public.png',fullPage:true});
await page.goto(base+'/');assert.equal(await page.locator('a[href="matematikbibliotek/"]').count(),1);
console.log(JSON.stringify({base,publicSearch:result.status,filterMs:result.ms,results:result.value.total,preview,noLogin:true,homepageLink:true,errors}));await browser.close();
