begin;

delete from public.flashcard_vocabulary;

insert into public.flashcard_vocabulary
  (language_code, word_id, danish, target, reading, accepted_answers, sort_order)
values
  ('el', 'sword', 'Sværd', 'σπαθί', 'spathi', '{}'::text[], 1),
  ('el', 'knife', 'Kniv', 'μαχαίρι', 'machairi', '{}'::text[], 2),
  ('el', 'fork', 'Gaffel', 'πιρούνι', 'pirouni', '{}'::text[], 3),
  ('el', 'plate', 'Tallerken', 'πιάτο', 'piato', '{}'::text[], 4),
  ('el', 'paper', 'Papir', 'χαρτί', 'charti', '{}'::text[], 5),
  ('el', 'metal', 'Metal', 'μέταλλο', 'metallo', '{}'::text[], 6),
  ('el', 'salt', 'Salt', 'αλάτι', 'alati', '{}'::text[], 7),
  ('el', 'water', 'Vand', 'νερό', 'nero', '{}'::text[], 8),
  ('el', 'food', 'Mad', 'φαγητό', 'fagito', '{}'::text[], 9),
  ('el', 'bear', 'Bjørn', 'αρκούδα', 'arkouda', '{}'::text[], 10),
  ('el', 'wolf', 'Ulv', 'λύκος', 'lykos', '{}'::text[], 11),
  ('el', 'dog', 'Hund', 'σκύλος', 'skylos', '{}'::text[], 12),
  ('el', 'horse', 'Hest', 'άλογο', 'alogo', '{}'::text[], 13),
  ('el', 'elephant', 'Elefant', 'ελέφαντας', 'elefantas', '{}'::text[], 14),
  ('la', 'sword', 'Sværd', 'gladius', 'gla-di-us', ARRAY['ensis']::text[], 1),
  ('la', 'knife', 'Kniv', 'culter', 'cul-ter', ARRAY['cultellus']::text[], 2),
  ('la', 'fork', 'Gaffel', 'furca', 'fur-ca', '{}'::text[], 3),
  ('la', 'plate', 'Tallerken', 'catillus', 'ca-til-lus', ARRAY['patina']::text[], 4),
  ('la', 'paper', 'Papir', 'charta', 'char-ta', '{}'::text[], 5),
  ('la', 'metal', 'Metal', 'metallum', 'me-tal-lum', '{}'::text[], 6),
  ('la', 'salt', 'Salt', 'sal', 'sal', '{}'::text[], 7),
  ('la', 'water', 'Vand', 'aqua', 'a-qua', '{}'::text[], 8),
  ('la', 'food', 'Mad', 'cibus', 'ci-bus', '{}'::text[], 9),
  ('la', 'bear', 'Bjørn', 'ursus', 'ur-sus', '{}'::text[], 10),
  ('la', 'wolf', 'Ulv', 'lupus', 'lu-pus', '{}'::text[], 11),
  ('la', 'dog', 'Hund', 'canis', 'ca-nis', '{}'::text[], 12),
  ('la', 'horse', 'Hest', 'equus', 'e-quus', '{}'::text[], 13),
  ('la', 'elephant', 'Elefant', 'elephantus', 'e-le-phan-tus', '{}'::text[], 14),
  ('ar', 'sword', 'Sværd', 'سيف', 'sayf', '{}'::text[], 1),
  ('ar', 'knife', 'Kniv', 'سكين', 'sikkin', '{}'::text[], 2),
  ('ar', 'fork', 'Gaffel', 'شوكة', 'shawka', '{}'::text[], 3),
  ('ar', 'plate', 'Tallerken', 'طبق', 'tabaq', '{}'::text[], 4),
  ('ar', 'paper', 'Papir', 'ورق', 'waraq', '{}'::text[], 5),
  ('ar', 'metal', 'Metal', 'معدن', 'madin', '{}'::text[], 6),
  ('ar', 'salt', 'Salt', 'ملح', 'milh', '{}'::text[], 7),
  ('ar', 'water', 'Vand', 'ماء', 'maa', '{}'::text[], 8),
  ('ar', 'food', 'Mad', 'طعام', 'taam', '{}'::text[], 9),
  ('ar', 'bear', 'Bjørn', 'دب', 'dubb', '{}'::text[], 10),
  ('ar', 'wolf', 'Ulv', 'ذئب', 'dhib', '{}'::text[], 11),
  ('ar', 'dog', 'Hund', 'كلب', 'kalb', '{}'::text[], 12),
  ('ar', 'horse', 'Hest', 'حصان', 'hisan', '{}'::text[], 13),
  ('ar', 'elephant', 'Elefant', 'فيل', 'fil', '{}'::text[], 14),
  ('ja', 'sword', 'Sværd', '剣', 'ken', ARRAY['けん', 'つるぎ', 'tsurugi']::text[], 1),
  ('ja', 'knife', 'Kniv', 'ナイフ', 'naifu', ARRAY['ないふ']::text[], 2),
  ('ja', 'fork', 'Gaffel', 'フォーク', 'fooku', ARRAY['ふぉーく']::text[], 3),
  ('ja', 'plate', 'Tallerken', '皿', 'sara', ARRAY['さら']::text[], 4),
  ('ja', 'paper', 'Papir', '紙', 'kami', ARRAY['かみ']::text[], 5),
  ('ja', 'metal', 'Metal', '金属', 'kinzoku', ARRAY['きんぞく']::text[], 6),
  ('ja', 'salt', 'Salt', '塩', 'shio', ARRAY['しお']::text[], 7),
  ('ja', 'water', 'Vand', '水', 'mizu', ARRAY['みず']::text[], 8),
  ('ja', 'food', 'Mad', '食べ物', 'tabemono', ARRAY['たべもの', '食物', 'shokumotsu', 'しょくもつ']::text[], 9),
  ('ja', 'bear', 'Bjørn', '熊', 'kuma', ARRAY['くま']::text[], 10),
  ('ja', 'wolf', 'Ulv', '狼', 'ookami', ARRAY['おおかみ']::text[], 11),
  ('ja', 'dog', 'Hund', '犬', 'inu', ARRAY['いぬ']::text[], 12),
  ('ja', 'horse', 'Hest', '馬', 'uma', ARRAY['うま']::text[], 13),
  ('ja', 'elephant', 'Elefant', '象', 'zou', ARRAY['ぞう']::text[], 14),
  ('sr', 'sword', 'Sværd', 'мач', 'mač', '{}'::text[], 1),
  ('sr', 'knife', 'Kniv', 'нож', 'nož', '{}'::text[], 2),
  ('sr', 'fork', 'Gaffel', 'виљушка', 'viljuška', '{}'::text[], 3),
  ('sr', 'plate', 'Tallerken', 'тањир', 'tanjir', '{}'::text[], 4),
  ('sr', 'paper', 'Papir', 'папир', 'papir', '{}'::text[], 5),
  ('sr', 'metal', 'Metal', 'метал', 'metal', '{}'::text[], 6),
  ('sr', 'salt', 'Salt', 'со', 'so', '{}'::text[], 7),
  ('sr', 'water', 'Vand', 'вода', 'voda', '{}'::text[], 8),
  ('sr', 'food', 'Mad', 'храна', 'hrana', '{}'::text[], 9),
  ('sr', 'bear', 'Bjørn', 'медвед', 'medved', '{}'::text[], 10),
  ('sr', 'wolf', 'Ulv', 'вук', 'vuk', '{}'::text[], 11),
  ('sr', 'dog', 'Hund', 'пас', 'pas', '{}'::text[], 12),
  ('sr', 'horse', 'Hest', 'коњ', 'konj', '{}'::text[], 13),
  ('sr', 'elephant', 'Elefant', 'слон', 'slon', '{}'::text[], 14),
  ('ru', 'sword', 'Sværd', 'меч', 'mech', '{}'::text[], 1),
  ('ru', 'knife', 'Kniv', 'нож', 'nozh', '{}'::text[], 2),
  ('ru', 'fork', 'Gaffel', 'вилка', 'vilka', '{}'::text[], 3),
  ('ru', 'plate', 'Tallerken', 'тарелка', 'tarelka', '{}'::text[], 4),
  ('ru', 'paper', 'Papir', 'бумага', 'bumaga', '{}'::text[], 5),
  ('ru', 'metal', 'Metal', 'металл', 'metall', '{}'::text[], 6),
  ('ru', 'salt', 'Salt', 'соль', 'sol', '{}'::text[], 7),
  ('ru', 'water', 'Vand', 'вода', 'voda', '{}'::text[], 8),
  ('ru', 'food', 'Mad', 'еда', 'yeda', '{}'::text[], 9),
  ('ru', 'bear', 'Bjørn', 'медведь', 'medved', '{}'::text[], 10),
  ('ru', 'wolf', 'Ulv', 'волк', 'volk', '{}'::text[], 11),
  ('ru', 'dog', 'Hund', 'собака', 'sobaka', '{}'::text[], 12),
  ('ru', 'horse', 'Hest', 'лошадь', 'loshad', '{}'::text[], 13),
  ('ru', 'elephant', 'Elefant', 'слон', 'slon', '{}'::text[], 14);

commit;
