ALTER TABLE public.flashcard_vocabulary DROP CONSTRAINT flashcard_vocabulary_sort_order_check;
ALTER TABLE public.flashcard_vocabulary ADD CONSTRAINT flashcard_vocabulary_sort_order_check CHECK (sort_order >= 1);

INSERT INTO public.flashcard_vocabulary (language_code,word_id,danish,target,reading,accepted_answers,sort_order) VALUES
('el','i','Jeg','εγώ','ego',ARRAY[]::text[],15),
('el','you','Du','εσύ','esy',ARRAY[]::text[],16),
('el','he','Han','αυτός','aftos',ARRAY[]::text[],17),
('el','she','Hun','αυτή','afti',ARRAY[]::text[],18),
('el','my','Min','μου','mou',ARRAY[]::text[],19),
('el','your','Din','σου','sou',ARRAY[]::text[],20),
('el','his','Hans','του','tou',ARRAY[]::text[],21),
('el','her','Hendes','της','tis',ARRAY[]::text[],22),
('el','their','Deres','τους','tous',ARRAY[]::text[],23),
('la','i','Jeg','ego','e-go',ARRAY[]::text[],15),
('la','you','Du','tu','tu',ARRAY[]::text[],16),
('la','he','Han','is','is',ARRAY['ille']::text[],17),
('la','she','Hun','ea','e-a',ARRAY['illa']::text[],18),
('la','my','Min','meus','me-us',ARRAY['mea','meum']::text[],19),
('la','your','Din','tuus','tu-us',ARRAY['tua','tuum']::text[],20),
('la','his','Hans','eius','ei-us',ARRAY[]::text[],21),
('la','her','Hendes','eius','ei-us',ARRAY[]::text[],22),
('la','their','Deres','eorum','e-o-rum',ARRAY['earum']::text[],23),
('ar','i','Jeg','أنا','ana',ARRAY['anaa']::text[],15),
('ar','you','Du','أنتَ','anta',ARRAY['أنتِ','anti']::text[],16),
('ar','he','Han','هو','huwa',ARRAY[]::text[],17),
('ar','she','Hun','هي','hiya',ARRAY[]::text[],18),
('ar','my','Min','ـي','ii',ARRAY['i','-i','-ii']::text[],19),
('ar','your','Din','ـكَ','ka',ARRAY['ـكِ','ki','-ka','-ki']::text[],20),
('ar','his','Hans','ـهُ','hu',ARRAY['-hu']::text[],21),
('ar','her','Hendes','ـها','ha',ARRAY['haa','-ha']::text[],22),
('ar','their','Deres','ـهم','hum',ARRAY['-hum','ـهن','hunna']::text[],23),
('ja','i','Jeg','私','watashi',ARRAY['わたし']::text[],15),
('ja','you','Du','あなた','anata',ARRAY[]::text[],16),
('ja','he','Han','彼','kare',ARRAY['かれ']::text[],17),
('ja','she','Hun','彼女','kanojo',ARRAY['かのじょ']::text[],18),
('ja','my','Min','私の','watashi no',ARRAY['わたしの','watashino']::text[],19),
('ja','your','Din','あなたの','anata no',ARRAY['anatano']::text[],20),
('ja','his','Hans','彼の','kare no',ARRAY['かれの','kareno']::text[],21),
('ja','her','Hendes','彼女の','kanojo no',ARRAY['かのじょの','kanojono']::text[],22),
('ja','their','Deres','彼らの','karera no',ARRAY['かれらの','彼女たちの','かのじょたちの','kanojotachi no','karerano']::text[],23),
('sr','i','Jeg','ја','ja',ARRAY[]::text[],15),
('sr','you','Du','ти','ti',ARRAY[]::text[],16),
('sr','he','Han','он','on',ARRAY[]::text[],17),
('sr','she','Hun','она','ona',ARRAY[]::text[],18),
('sr','my','Min','мој','moj',ARRAY['моја','моје','moja','moje']::text[],19),
('sr','your','Din','твој','tvoj',ARRAY['твоја','твоје','tvoja','tvoje']::text[],20),
('sr','his','Hans','његов','njegov',ARRAY['његова','његово','njegova','njegovo']::text[],21),
('sr','her','Hendes','њен','njen',ARRAY['њена','њено','njena','njeno']::text[],22),
('sr','their','Deres','њихов','njihov',ARRAY['њихова','њихово','njihova','njihovo']::text[],23),
('ru','i','Jeg','я','ya',ARRAY['ja']::text[],15),
('ru','you','Du','ты','ty',ARRAY[]::text[],16),
('ru','he','Han','он','on',ARRAY[]::text[],17),
('ru','she','Hun','она','ona',ARRAY[]::text[],18),
('ru','my','Min','мой','moy',ARRAY['моя','моё','мои','moi','moja','moya','moe','moyo','moi']::text[],19),
('ru','your','Din','твой','tvoy',ARRAY['твоя','твоё','твои','tvoi','tvoya','tvoja','tvoyo','tvoe']::text[],20),
('ru','his','Hans','его','yego',ARRAY['ego']::text[],21),
('ru','her','Hendes','её','yeyo',ARRAY['ее','eyo','ejo','yoyo']::text[],22),
('ru','their','Deres','их','ikh',ARRAY['ih']::text[],23)
ON CONFLICT (language_code,word_id) DO UPDATE SET danish=EXCLUDED.danish,target=EXCLUDED.target,reading=EXCLUDED.reading,accepted_answers=EXCLUDED.accepted_answers,sort_order=EXCLUDED.sort_order;