create table if not exists public.flashcard_vocabulary (
  language_code text not null
    check (language_code in ('el', 'la', 'ar', 'ja', 'sr', 'ru')),
  word_id text not null,
  danish text not null,
  target text not null,
  reading text not null default '',
  accepted_answers text[] not null default '{}',
  sort_order smallint not null
    check (sort_order between 1 and 21),
  primary key (language_code, word_id),
  unique (language_code, sort_order)
);

alter table public.flashcard_vocabulary enable row level security;

grant select on public.flashcard_vocabulary to anon, authenticated;

drop policy if exists "Public can read flashcard vocabulary"
  on public.flashcard_vocabulary;

create policy "Public can read flashcard vocabulary"
  on public.flashcard_vocabulary
  for select
  to anon, authenticated
  using (true);

insert into public.flashcard_vocabulary
  (language_code, word_id, danish, target, reading, accepted_answers, sort_order)
values
  ('el', 'chair', 'Stol', 'καρέκλα', 'karekla', '{}', 1),
  ('el', 'table', 'Bord', 'τραπέζι', 'trapezi', '{}', 2),
  ('el', 'pencil', 'Blyant', 'μολύβι', 'molyvi', '{}', 3),
  ('el', 'boy', 'Dreng', 'αγόρι', 'agori', '{}', 4),
  ('el', 'girl', 'Pige', 'κορίτσι', 'koritsi', '{}', 5),
  ('el', 'man', 'Mand', 'άνδρας', 'andras', '{}', 6),
  ('el', 'woman', 'Kvinde', 'γυναίκα', 'gynaika', '{}', 7),
  ('el', 'house', 'Hus', 'σπίτι', 'spiti', '{}', 8),
  ('el', 'stone', 'Sten', 'πέτρα', 'petra', '{}', 9),
  ('el', 'iron', 'Jern', 'σίδηρος', 'sidiros', ARRAY['σίδερο', 'sidero']::text[], 10),
  ('el', 'car', 'Bil', 'αυτοκίνητο', 'aftokinito', '{}', 11),
  ('el', 'red', 'Rød', 'κόκκινος', 'kokkinos', '{}', 12),
  ('el', 'blue', 'Blå', 'μπλε', 'ble', '{}', 13),
  ('el', 'green', 'Grøn', 'πράσινος', 'prasinos', '{}', 14),
  ('el', 'yellow', 'Gul', 'κίτρινος', 'kitrinos', '{}', 15),
  ('el', 'black', 'Sort', 'μαύρος', 'mavros', '{}', 16),
  ('el', 'white', 'Hvid', 'λευκός', 'lefkos', ARRAY['άσπρος', 'aspros']::text[], 17),
  ('el', 'big', 'Stor', 'μεγάλος', 'megalos', '{}', 18),
  ('el', 'small', 'Lille', 'μικρός', 'mikros', '{}', 19),
  ('el', 'warm', 'Varm', 'ζεστός', 'zestos', '{}', 20),
  ('el', 'cold', 'Kold', 'κρύος', 'kryos', '{}', 21),
  ('la', 'chair', 'Stol', 'sella', '', '{}', 1),
  ('la', 'table', 'Bord', 'mensa', '', ARRAY['tabula']::text[], 2),
  ('la', 'pencil', 'Blyant', 'stilus', '', ARRAY['graphium', 'pencillum']::text[], 3),
  ('la', 'boy', 'Dreng', 'puer', '', '{}', 4),
  ('la', 'girl', 'Pige', 'puella', '', '{}', 5),
  ('la', 'man', 'Mand', 'vir', '', '{}', 6),
  ('la', 'woman', 'Kvinde', 'mulier', '', '{}', 7),
  ('la', 'house', 'Hus', 'domus', '', '{}', 8),
  ('la', 'stone', 'Sten', 'lapis', '', '{}', 9),
  ('la', 'iron', 'Jern', 'ferrum', '', '{}', 10),
  ('la', 'car', 'Bil', 'autocinetum', '', ARRAY['currus automobilis', 'automobilis']::text[], 11),
  ('la', 'red', 'Rød', 'ruber', '', '{}', 12),
  ('la', 'blue', 'Blå', 'caeruleus', '', '{}', 13),
  ('la', 'green', 'Grøn', 'viridis', '', '{}', 14),
  ('la', 'yellow', 'Gul', 'flavus', '', '{}', 15),
  ('la', 'black', 'Sort', 'niger', '', '{}', 16),
  ('la', 'white', 'Hvid', 'albus', '', '{}', 17),
  ('la', 'big', 'Stor', 'magnus', '', '{}', 18),
  ('la', 'small', 'Lille', 'parvus', '', '{}', 19),
  ('la', 'warm', 'Varm', 'calidus', '', '{}', 20),
  ('la', 'cold', 'Kold', 'frigidus', '', '{}', 21),
  ('ar', 'chair', 'Stol', 'كرسي', 'kursi', '{}', 1),
  ('ar', 'table', 'Bord', 'طاولة', 'tawila', '{}', 2),
  ('ar', 'pencil', 'Blyant', 'قلم رصاص', 'qalam rasas', '{}', 3),
  ('ar', 'boy', 'Dreng', 'ولد', 'walad', '{}', 4),
  ('ar', 'girl', 'Pige', 'فتاة', 'fata', ARRAY['بنت', 'bint']::text[], 5),
  ('ar', 'man', 'Mand', 'رجل', 'rajul', '{}', 6),
  ('ar', 'woman', 'Kvinde', 'امرأة', 'imraa', '{}', 7),
  ('ar', 'house', 'Hus', 'بيت', 'bayt', '{}', 8),
  ('ar', 'stone', 'Sten', 'حجر', 'hajar', '{}', 9),
  ('ar', 'iron', 'Jern', 'حديد', 'hadid', '{}', 10),
  ('ar', 'car', 'Bil', 'سيارة', 'sayyara', '{}', 11),
  ('ar', 'red', 'Rød', 'أحمر', 'ahmar', '{}', 12),
  ('ar', 'blue', 'Blå', 'أزرق', 'azraq', '{}', 13),
  ('ar', 'green', 'Grøn', 'أخضر', 'akhdar', '{}', 14),
  ('ar', 'yellow', 'Gul', 'أصفر', 'asfar', '{}', 15),
  ('ar', 'black', 'Sort', 'أسود', 'aswad', '{}', 16),
  ('ar', 'white', 'Hvid', 'أبيض', 'abyad', '{}', 17),
  ('ar', 'big', 'Stor', 'كبير', 'kabir', '{}', 18),
  ('ar', 'small', 'Lille', 'صغير', 'saghir', '{}', 19),
  ('ar', 'warm', 'Varm', 'دافئ', 'dafi', '{}', 20),
  ('ar', 'cold', 'Kold', 'بارد', 'barid', '{}', 21),
  ('ja', 'chair', 'Stol', '椅子', 'いす', ARRAY['isu']::text[], 1),
  ('ja', 'table', 'Bord', 'テーブル', 'てーぶる', ARRAY['teeburu']::text[], 2),
  ('ja', 'pencil', 'Blyant', '鉛筆', 'えんぴつ', ARRAY['enpitsu']::text[], 3),
  ('ja', 'boy', 'Dreng', '男の子', 'おとこのこ', ARRAY['otokonoko']::text[], 4),
  ('ja', 'girl', 'Pige', '女の子', 'おんなのこ', ARRAY['onnanoko']::text[], 5),
  ('ja', 'man', 'Mand', '男性', 'だんせい', ARRAY['dansei']::text[], 6),
  ('ja', 'woman', 'Kvinde', '女性', 'じょせい', ARRAY['josei']::text[], 7),
  ('ja', 'house', 'Hus', '家', 'いえ', ARRAY['ie', 'uchi']::text[], 8),
  ('ja', 'stone', 'Sten', '石', 'いし', ARRAY['ishi']::text[], 9),
  ('ja', 'iron', 'Jern', '鉄', 'てつ', ARRAY['tetsu']::text[], 10),
  ('ja', 'car', 'Bil', '車', 'くるま', ARRAY['kuruma']::text[], 11),
  ('ja', 'red', 'Rød', '赤い', 'あかい', ARRAY['akai']::text[], 12),
  ('ja', 'blue', 'Blå', '青い', 'あおい', ARRAY['aoi']::text[], 13),
  ('ja', 'green', 'Grøn', '緑色', 'みどりいろ', ARRAY['midoriiro', '緑']::text[], 14),
  ('ja', 'yellow', 'Gul', '黄色', 'きいろ', ARRAY['kiiro', '黄色い', 'きいろい', 'kiiroi']::text[], 15),
  ('ja', 'black', 'Sort', '黒い', 'くろい', ARRAY['kuroi']::text[], 16),
  ('ja', 'white', 'Hvid', '白い', 'しろい', ARRAY['shiroi']::text[], 17),
  ('ja', 'big', 'Stor', '大きい', 'おおきい', ARRAY['ookii']::text[], 18),
  ('ja', 'small', 'Lille', '小さい', 'ちいさい', ARRAY['chiisai']::text[], 19),
  ('ja', 'warm', 'Varm', '暖かい', 'あたたかい', ARRAY['atatakai', '温かい']::text[], 20),
  ('ja', 'cold', 'Kold', '冷たい', 'つめたい', ARRAY['tsumetai', '寒い', 'さむい', 'samui']::text[], 21),
  ('sr', 'chair', 'Stol', 'столица', 'stolica', '{}', 1),
  ('sr', 'table', 'Bord', 'сто', 'sto', '{}', 2),
  ('sr', 'pencil', 'Blyant', 'оловка', 'olovka', '{}', 3),
  ('sr', 'boy', 'Dreng', 'дечак', 'dečak', '{}', 4),
  ('sr', 'girl', 'Pige', 'девојчица', 'devojčica', '{}', 5),
  ('sr', 'man', 'Mand', 'мушкарац', 'muškarac', '{}', 6),
  ('sr', 'woman', 'Kvinde', 'жена', 'žena', '{}', 7),
  ('sr', 'house', 'Hus', 'кућа', 'kuća', '{}', 8),
  ('sr', 'stone', 'Sten', 'камен', 'kamen', '{}', 9),
  ('sr', 'iron', 'Jern', 'гвожђе', 'gvožđe', '{}', 10),
  ('sr', 'car', 'Bil', 'аутомобил', 'automobil', '{}', 11),
  ('sr', 'red', 'Rød', 'црвен', 'crven', '{}', 12),
  ('sr', 'blue', 'Blå', 'плав', 'plav', '{}', 13),
  ('sr', 'green', 'Grøn', 'зелен', 'zelen', '{}', 14),
  ('sr', 'yellow', 'Gul', 'жут', 'žut', '{}', 15),
  ('sr', 'black', 'Sort', 'црн', 'crn', '{}', 16),
  ('sr', 'white', 'Hvid', 'бео', 'beo', '{}', 17),
  ('sr', 'big', 'Stor', 'велики', 'veliki', ARRAY['velik']::text[], 18),
  ('sr', 'small', 'Lille', 'мали', 'mali', '{}', 19),
  ('sr', 'warm', 'Varm', 'топао', 'topao', '{}', 20),
  ('sr', 'cold', 'Kold', 'хладан', 'hladan', '{}', 21),
  ('ru', 'chair', 'Stol', 'стул', 'stul', '{}', 1),
  ('ru', 'table', 'Bord', 'стол', 'stol', '{}', 2),
  ('ru', 'pencil', 'Blyant', 'карандаш', 'karandash', '{}', 3),
  ('ru', 'boy', 'Dreng', 'мальчик', 'malchik', '{}', 4),
  ('ru', 'girl', 'Pige', 'девочка', 'devochka', '{}', 5),
  ('ru', 'man', 'Mand', 'мужчина', 'muzhchina', '{}', 6),
  ('ru', 'woman', 'Kvinde', 'женщина', 'zhenshchina', '{}', 7),
  ('ru', 'house', 'Hus', 'дом', 'dom', '{}', 8),
  ('ru', 'stone', 'Sten', 'камень', 'kamen', '{}', 9),
  ('ru', 'iron', 'Jern', 'железо', 'zhelezo', '{}', 10),
  ('ru', 'car', 'Bil', 'машина', 'mashina', ARRAY['автомобиль', 'avtomobil']::text[], 11),
  ('ru', 'red', 'Rød', 'красный', 'krasnyy', '{}', 12),
  ('ru', 'blue', 'Blå', 'синий', 'siniy', '{}', 13),
  ('ru', 'green', 'Grøn', 'зелёный', 'zelenyy', '{}', 14),
  ('ru', 'yellow', 'Gul', 'жёлтый', 'zheltyy', '{}', 15),
  ('ru', 'black', 'Sort', 'чёрный', 'chernyy', '{}', 16),
  ('ru', 'white', 'Hvid', 'белый', 'belyy', '{}', 17),
  ('ru', 'big', 'Stor', 'большой', 'bolshoy', '{}', 18),
  ('ru', 'small', 'Lille', 'маленький', 'malenkiy', '{}', 19),
  ('ru', 'warm', 'Varm', 'тёплый', 'teplyy', '{}', 20),
  ('ru', 'cold', 'Kold', 'холодный', 'kholodnyy', '{}', 21)
on conflict (language_code, word_id) do update set
  danish = excluded.danish,
  target = excluded.target,
  reading = excluded.reading,
  accepted_answers = excluded.accepted_answers,
  sort_order = excluded.sort_order;

